# Gets triggered upon the creation of a new tag
on:
  push:
    tags:
      - "v*" # Matches tags with the name "v*", i.e. v1.0, v20.15.10

name: Generate Website and add as Release
# Performs the following steps:
#   - Install all dependencies (and caches them for future runs)
#   - Builds the website
#   - Compresses the generated website
#   - Packages the generated website
#   - Creates a release based on the originating tag
#   - Attaches the package to the release
jobs:
  build:
    name: Generate Website and add as Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Build with Jekyll
        run: |
          bundle exec jekyll build -d _site/
        env:
          JEKYLL_ENV: production

      - name: Install Minify
        run: |
          sudo apt-get update
          sudo apt-get install minify
      - name: Compress entire website
        run: |
          minify --all --html-keep-document-tags --html-keep-end-tags -r -o _site/ _site/

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install PurgeCSS and Terser
        run: |
          npm install -g purgecss
          npm install -g terser
      - name: Compress CSS with PurgeCSS
        run: |
          purgecss --config purgecss.config.js
      - name: Compress JavaScript with Terser
        run: |
          terser _site/assets/js/main.js --compress ecma=2015,top_retain=window.conference --mangle --comments false --output _site/assets/js/main.js

      - name: Package generated website
        run: |
          cd _site/
          zip -r ../website.zip *
          cd ../

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v2
        with:
          files: ./website.zip
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
