name: Generate Website and add as Release
# Gets triggered upon the creation of a new tag
on:
  push:
    tags:
    - 'v*' # Matches tags with the name "v*", i.e. v1.0, v20.15.10
# Performs the following steps:
#   - Install all dependencies (and caches them for future runs)
#   - Builds the website
#   - Compresses the generated website
#   - Packages the generated website
#   - Creates a release based on the originating tag
#   - Attaches the package to the release
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1

      - name: Ruby Cache
        id: cache_ruby
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Install Bundler and Jekyll
        if: steps.cache_ruby.outputs.cache-hit != 'true'
        run: |
          gem install bundler
          bundle install --path vendor/bundle

      - name: Build website
        run: |
          bundle exec jekyll build -d _site/

      - name: Install Minify
        run: |
          sudo apt-get update
          sudo apt-get install minify

      - name: Compress entire website
        run: |
          minify --all --html-keep-document-tags --html-keep-end-tags -r -o _site_compressed/ _site/

      - name: Package generated website
        run: |
          cd _site_compressed/
          zip -r ../website.zip *
          cd ../

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload zipped Website as Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./website.zip
          asset_name: website.zip
          asset_content_type: application/zip
