name: Build & Publish Ruby Gem
# Performs the following steps:
#   - Sets the environment up
#   - Builds the gem
#   - Uploads the gem to RubyGem
#   - Creates a GitHub release and attaches the gem to it

# Gets triggered upon the creation of a new tag
on:
  push:
    tags:
      - "v*" # Matches tags with the name "v*", i.e. v1.0, v20.15.10

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      - name: Set up Ruby 3.3
        id: setup_ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Publish to RubyGems
        id: publish_rubygems
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          echo "---" >> $HOME/.gem/credentials
          echo ":rubygems_api_key: ${RUBYGEMS_API_KEY}" >> $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
          mv *.gem jekyll-theme-conference.gem

      - name: Create Release and Upload Asset
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: jekyll-theme-conference.gem
